name: timeless_core
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # --- Oyun Motoru & Ses (AJANIN İSTEDİĞİ GİBİ GÜNCELLENDİ) ---
  flame: ^1.20.0          # 1.18'den 1.20'ye yükseltildi (Kritik Performans ve Fizik Güncellemesi)
  flame_audio: ^2.2.0     # Flame 1.20 ile tam uyumlu çalışması için yükseltildi
  
  # --- Gelir Modelleri (Reklam & Satın Alma) ---
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.0  # Yeni eklediğimiz Satın Alma motoru
  
  # --- Veri Saklama ---
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0    # Kod kalite kontrolcüsü modern sürüme çekildi
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/sfx/
    - assets/translations/

# --- İkon Ayarları ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/icon.png"

# --- Açılış Ekranı (Splash) ---
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.jpg
  android_12:
    image: assets/images/android12splash.png
    color: "#000000"